# Generated by Django 5.2.8 on 2025-11-14 06:32

import core.models
import datetime
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicBlog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date_created", models.DateTimeField()),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("image", models.ImageField(upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=150, unique=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", core.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name="ArticleAd",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("article_topic", models.CharField(max_length=255)),
                (
                    "seo_keywords",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("research_material", models.TextField(blank=True, null=True)),
                ("article_length", models.CharField(max_length=255)),
                (
                    "feature_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("response", models.TextField(blank=True, null=True)),
                ("date_created", models.DateTimeField(default=datetime.date.today)),
                ("module_credit_cost", models.IntegerField(default=0)),
                ("title", models.TextField(blank=True)),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("Public", "Public"),
                            ("Private", "Private"),
                            ("Restricted", "Restricted"),
                        ],
                        default="Private",
                        max_length=100,
                    ),
                ),
                ("last_edit", models.DateTimeField(null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CustomDoc",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField(blank=True)),
                ("module_credit_cost", models.IntegerField(default=0)),
                ("date_created", models.DateTimeField(default=datetime.date.today)),
                ("title", models.TextField(blank=True)),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("Public", "Public"),
                            ("Private", "Private"),
                            ("Restricted", "Restricted"),
                        ],
                        default="Private",
                        max_length=100,
                    ),
                ),
                ("last_edit", models.DateTimeField(null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmailMarketing",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("feature_name", models.CharField(max_length=255, null=True)),
                ("to_pitch", models.TextField(blank=True)),
                ("our_offering", models.TextField(blank=True)),
                ("prospect_name", models.CharField(blank=True, max_length=255)),
                ("prospect_company", models.CharField(blank=True, max_length=255)),
                ("prospect_niche", models.TextField(blank=True)),
                ("prospect_contact_about", models.TextField(blank=True)),
                ("cta", models.CharField(blank=True, max_length=255)),
                ("your_name", models.CharField(blank=True, max_length=255)),
                ("response", models.TextField(blank=True)),
                ("module_credit_cost", models.IntegerField(default=0)),
                ("date_created", models.DateTimeField(default=datetime.date.today)),
                ("title", models.TextField(blank=True)),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("Public", "Public"),
                            ("Private", "Private"),
                            ("Restricted", "Restricted"),
                        ],
                        default="Private",
                        max_length=100,
                    ),
                ),
                ("last_edit", models.DateTimeField(null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FacebookAd",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("service_or_product", models.CharField(blank=True, max_length=255)),
                (
                    "offering_uniqueness",
                    models.TextField(
                        blank=True, help_text="What makes our product/service unique"
                    ),
                ),
                ("ideal_market", models.CharField(blank=True, max_length=255)),
                ("cta", models.CharField(blank=True, max_length=155)),
                (
                    "review_on",
                    models.TextField(
                        blank=True,
                        help_text="The review your product received copy pasted",
                    ),
                ),
                (
                    "reviewer",
                    models.CharField(
                        blank=True,
                        help_text="Name of person who left the review",
                        max_length=255,
                    ),
                ),
                (
                    "reviewed_item",
                    models.TextField(
                        blank=True, help_text="Your Service/Product that got the review"
                    ),
                ),
                ("feature_name", models.CharField(max_length=255)),
                ("response", models.TextField(blank=True, null=True)),
                ("title", models.TextField(blank=True)),
                ("date_created", models.DateTimeField(default=datetime.date.today)),
                ("module_credit_cost", models.IntegerField(default=0)),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("Public", "Public"),
                            ("Private", "Private"),
                            ("Restricted", "Restricted"),
                        ],
                        default="Private",
                        max_length=100,
                    ),
                ),
                ("last_edit", models.DateTimeField(null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LinkedinAd",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("feature_name", models.CharField(max_length=255)),
                ("feature_fields", models.JSONField(default=dict)),
                ("response", models.TextField(blank=True, null=True)),
                ("date_created", models.DateTimeField(default=datetime.date.today)),
                ("module_credit_cost", models.IntegerField(default=0)),
                ("title", models.TextField(blank=True)),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("Public", "Public"),
                            ("Private", "Private"),
                            ("Restricted", "Restricted"),
                        ],
                        default="Private",
                        max_length=100,
                    ),
                ),
                ("last_edit", models.DateTimeField(null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LinkedinComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("feature_name", models.CharField(max_length=255, null=True)),
                ("post", models.TextField(blank=True)),
                ("points_to_mention", models.TextField(blank=True)),
                ("response", models.TextField(blank=True)),
                (
                    "credit_used",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        default=0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "module_credit_cost",
                    models.DecimalField(decimal_places=1, default=0, max_digits=10),
                ),
                ("date_created", models.DateField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
