# Generated by Django 5.2.8 on 2026-01-26 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="facebookad",
            name="image",
            field=models.TextField(blank=True, null=True),
        ),
    ]
