# Generated by Django 5.2.8 on 2025-12-06 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookad',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
